exclude: ["archetypes", "exampleSite", "layouts", "theme.toml"]

module:
  hugoVersion:
    extended: false
    max: ""
    min: ""
params:
    skin: "macintosh"

title: "mmm neofeed d' ja"
tags: ["neofeed", "neocities", "hugotemplate", "altwit"]

