exclude: ["archetypes", "exampleSite", "layouts", "theme.toml"]
baseURL: "https://theyrej.neocities.org/"
languageCode: "en-us"
paginate: 9 
title: "mmm neofeed d' ja"
tags: ["neofeed", "neocities", "hugotemplate", "altwit"]

taxonomies:
  tag: "tags"
author:
  name: "Reija Clemmensen"
  image: "image link here"
  about: "I am the internet and you can too!"
module:
  hugoVersion:
    extended: false
    max: ""
    min: ""
params:
    skin: "macintosh"
    githubuser: "wh0pper"
permalinks:
  feed: "/:title/"
outputs:
  home: ["HTML", "JSON", "RSS"]

